<?php
/* Template Name: Çözüm Ortakları */
get_header();

// Entegratör listesi
$integrators = [
    'https://ikasa.com.tr/wp-content/uploads/2025/01/abase.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/adam.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/aktif-barkod.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/amni.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/ariapos.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/barsoft.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/bay-entegre.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/boylam-yazilim.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/bta-1.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/camlica-barkod.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/datakod.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/e-yaz.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/farmakom.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/farmasyon.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/fastrest.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/fenix-software.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/gelisim.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/genresman.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/gizsoft.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/interprobis.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/iremsoft.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/kalem-yazilimm.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/logo.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/med-data.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/mikro-yazilim.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/pargesoft.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/paypad.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/petkom.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/protel.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/rbs-retail.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/restopos.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/robot-pos.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/sarpos.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/softmed.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/talya.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/tebeos.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/tera-yazilim.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/tria.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/uc-boyutlu.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/uyumsoft.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/vega-yazilim.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/01/yetkin-soft.jpg',
    'https://ikasa.com.tr/wp-content/uploads/2025/02/eray_back.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/02/naspos_back2.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/02/ritapos_jpg.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/5A-Bilgisayar.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/ADD-Bilsim-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Adisyo-bilisim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Alaca-yazilim1.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Alfapos.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Antsis-Yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Argedan-Bilisim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Arken-Yazilim-JaviPos.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Arniva-Yazilim-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Atlantis-Yazilim-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/BAYTperfectus.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Benim-Pos.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Biletinial.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Bilge-Karinca-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Bilmed-Yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Biltek-Bilisim-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/CPM-Yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Canias-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Cenasis-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Dara-Yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Datamaris.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Datapark-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Desen-ERP-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Dia-Yazilim-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Dijitika-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Donbay-yazilim-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/ERP12Yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Ebilgi.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Echopos-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Elca-Kozmetik-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Erise-Farmasist-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Eropa-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Evet-yazilim-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Eyosoft-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Femsoft-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Finetech.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Gurcom-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/HDS-Otomasyon.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/HTG-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Hesapbilir-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Hitit-Yazilim-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Hobi-bilisim-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Ilon-yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Kervansanal.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Kerzzpos-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Korgun-Yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Led-Yazilim-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Link-bilgisayar.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Lotus-pecas.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/MK-Yazilim-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Mava.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Mavi-Lego.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Menejer.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Mentor-yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Menulux-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Mevki-yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Nebil-yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Nefa-Yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Negmar.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Nivogo-removebg-preview.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Piksel-mutfak.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Posstart-removebg-preview.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Prodev.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/ROP-gUNCEL.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/RST-Yazilim-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Restapp.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Restroid.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Ritmus-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Rmos-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Rox-yazilim-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Sades-yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Saruhan-Holding.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Semtek-yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Sentez-yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Sepet-Takip-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Servissoft.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Sfisoft-removebg-preview.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Shiji.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Sinerji-Bilisim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/SuitablePos.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Suitpos.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Supplementer-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/TZ-Yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Tebeos.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Teknikpos-removebg-preview.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/TeknoERP-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Teknolya-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Tera-Yazilim-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Tesco_Kipa.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Tezzro-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/TikaBasa.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Torun.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Toya.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Vega-Yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Venz-Teknoloji-Guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Vinya_Bilisim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Web-ticari-yazilim-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/YetkinSoft.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/Zensoft-Yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/adanet.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/akin-soft.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/arkhe-yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/barkod-bilgi-islem.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/barkomatik.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/bate-bilisim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/bilnex.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/bilsoft-yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/botaniklogo1.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/diebold.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/dinamik-barkod.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/dinosoft.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/dizayn-yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/e-yaz-yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/enpos.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/fornextLogo.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/gun-is-yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/ibaysoft-yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/nebim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/oryaz-yazilim.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/pickpos-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/regedit-guncel.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/sambapos_logo.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/talya_bilisim-removebg-preview.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/tria.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/uyumsoft.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/weeb-group.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/winsell.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/07/yelsoft.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/08/deneb1.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/09/Rasard.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/09/yeppos-1.png',
    'https://ikasa.com.tr/wp-content/uploads/2025/12/gopos.png',
    'https://ikasa.com.tr/wp-content/uploads/2026/01/2BTBilisim.png',
    'https://ikasa.com.tr/wp-content/uploads/2026/01/OrionposLogo.png',
];
?>

<div class="page-header py-5 bg-light mb-5">
    <div class="container">
        <h1 class="text-center display-4 mb-3">Çözüm Ortakları</h1>
        <p class="text-center lead text-muted">Birlikte çalışmaktan gurur duyduğumuz iş ortaklarımız</p>
    </div>
</div>

<div class="container mb-5">
    <div class="row row-cols-2 row-cols-md-4 row-cols-lg-6 g-4">
        <?php foreach ($integrators as $logo_url): ?>
            <div class="col">
                <div class="card h-100 border-0 shadow-sm align-items-center justify-content-center p-3 hover-effect">
                    <img src="<?php echo esc_url($logo_url); ?>" 
                         class="img-fluid" 
                         alt="Çözüm Ortağı" 
                         style="max-height: 80px; object-fit: contain; width: 100%;">
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<style>
    .hover-effect {
        transition: transform 0.3s ease, box-shadow 0.3s ease;
    }
    .hover-effect:hover {
        transform: translateY(-5px);
        box-shadow: 0 .5rem 1rem rgba(0,0,0,.15)!important;
    }
</style>

<?php get_footer(); ?>
